version: "3.9"
  
volumes:
  blazegraph_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './volumes/blazegraph'


services:
  neutron-adapter:
    build:
      context: "."
    # command: npm start
    networks:
      - default
    environment:
      - update_time=11:30


  sepa:
    image: vaimee/sepa:v0.13.0
    networks:
      - default
    environment:
      - endpoint=/endpoints/endpoint-blazegraph.jpar
      - host=blazegraph
      - Dlog4j.configurationFile=log4j2-debug.xml
      - JMX_HOSTNAME=localhost
      - JMX_PORT=7090
    ports:
      - 8000:8000
      - 9000:9000
      - 7090:7090
    depends_on:
      - blazegraph

  blazegraph:
    image: nawer/blazegraph:2.1.5
    volumes:
      - blazegraph_data:/var/lib/jetty
    networks:
      - default
    environment:
      - JAVA_XMS=512m
      - JAVA_XMX=1g 